
# DOCUMENTATION
# https://swagger.io/docs/specification/about/

# ===================================== ENDPOINT TEMPLATE =====================================

# /ENDPOINT_NAME/{id}:
#     post:
#       tags: 
#         - ENDPOINT_CATEGORY
#       summary: SUMMARY
#       description: OPTIONAL_DESCRIPTION

#       parameters:
#         - in: path
#           name: id   # Must be the same name as in the path
#           required: true
#           schema:
#             type: integer
#             minimum: 10 # e.g. anything below 10 is not accepted... we probably won't need this
#           description: The user ID
#         - in: query
#           name: QUERY_PARAM_NAME
#           required: false
#           schema:
#             default: 1
#             type: integer #(array, boolean, integer, number, object, string)
#           description: PARAM_DESCRIPTION

#       requestBody:
#         description: OPTIONAL_DESCRIPTION
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/COMPONENT_NAME'
#           application/x-www-form-urlencoded:
#             schema:
#               type: object
#               properties:
#                 name:          # <--- form field name
#                   type: string
#                 fav_number:    # <--- form field name
#                   type: integer
#               required:
#                 - name
#                 - email
#           text/plain:
#             schema:
#               type: string

#       responses:
#         '200': # 201, 401 etc.
#           description: RESPONSE_DESCRIPTION
#           content:
#             application/json:
#               schema: # Can also return a ref to a component
#                 type: array #(array, boolean, integer, number, object, string)
#                 items: 
#                   type: string
#                   example: "EXAMPLE_STRING"


# ===================================== COMPONENT TEMPLATE ====================================

# COMPONENT_NAME:
#       type: object
#       properties:
#         id:
#           type: integer
#         name:
#           type: string          


# ====================================== API DESCRIPTION ======================================
openapi: 3.0.0
info:
  title: NameTBD API
  description: Description
  version: 1.0.0
paths:

  # =============== FORMS
  /forms/{FormID}:
    get:
      tags:
        - Form
      summary: Get an empty form

      parameters:
        - in: path
          name: FormID
          required: true
          schema:
            $ref: '#/components/schemas/FormID'

      responses:
        '201':
          $ref: '#/components/responses/201'
        '404':
          $ref: '#/components/responses/404'

  /forms:
    get:
      tags:
        - Form
      summary: Get a list of forms

      responses:
        '200':
          $ref: '#/components/responses/SDCFormResponseList'
        '404':
          $ref: '#/components/responses/404'

    post:
      tags:
        - Form
      summary: Add a new form
      requestBody:
        $ref: '#/components/requestBodies/SDCFormBody'

      responses:
        '200':
          $ref: '#/components/responses/SDCFormList'

  # =============== FORM RESPONSES
  /form-responses/{FormResponseID}:
    get:
      tags:
        - Form Responses
      summary: Get a specific form response

      parameters:
        - in: path
          name: FormResponseID
          required: true
          schema:
            $ref: '#/components/schemas/FormResponseID'

      responses:
        '200':
          $ref: '#/components/responses/SDCFormResponse'
        '404':
          $ref: '#/components/responses/404'
  /form-responses/search:
    get:
      tags:
        - Form Responses
      summary: Search for form responses
      responses:
        '200':
          $ref: '#/components/responses/SDCFormResponseList'
  /form-responses:
    post:
      tags:
        - Form Responses
      summary: Create a form response
      requestBody:
        $ref: '#/components/requestBodies/SDCFormResponseBody'

      responses:
        '201':
          $ref: '#/components/responses/201'


components:
  schemas:
    DiagnosticProcedureID:
      type: number
      description: "Identifier for medical observation or test result"
    PatientID:
      type: number
      description: "Identifier for a patient"
    FormFillerID:
      type: number
      description: "Identifier for a doctor or other clinician"
    FormID:
      type: number
      description: "Identifier for an SDC form template"
    FormResponseID:
      type: number
      description: "Identifier for a specific form response"
    SDCQuestion:
      type: object
      description: "A question in a form"
    SDCForm:
      type: object
      description: "An object that represents the structured data in an SDC xml file"
      properties:
        FormResponseID:
          $ref: '#/components/schemas/FormResponseID'
        FormID:
          $ref: '#/components/schemas/FormID'
        DiagnosticProdedureID:
          $ref: '#/components/schemas/DiagnosticProcedureID'
        PatientID:
          $ref: '#/components/schemas/PatientID'
        FormFillerID:
          $ref: '#/components/schemas/FormFillerID'
    SDCFormMetaData:
      type: object
      description: "An object that contains meta data form each form"
      properties:
        FormID:
          $ref: '#/components/schemas/FormID'

  requestBodies:
    SDCFormResponseBody:
      description: "A request body for submitting a form response"
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SDCForm'
    SDCFormBody:
      description: "A request body for uploading an xml form"
      required: true
      content: {}

  responses:
    201:
      description: "Successfully created"
    400:
      description: "Bad request"
    401:
      description: "Unauthorized"
    404:
      description: "Resource not found"
    403:
      description: "Forbidden"
    SDCFormResponse:
      description: "An SDC Form"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SDCForm'
    SDCFormResponseList:
      description: "A list of SDC Forms"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SDCForm'
    SDCFormList:
      description: "A list of SDC Forms"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SDCFormMetaData'


          
          
          
          
          
          
          
          